// This file was autogenerated by bower_components/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/depA.js', ['pow.a'], ['goog.string', 'pow.b', 'pow.c'], false);
goog.addDependency('../../../../src/depB.js', ['pow.b'], [], false);
goog.addDependency('../../../../src/depC.js', ['pow.c'], ['pow.d'], false);
goog.addDependency('../../../../src/depD.js', ['pow.d'], [], false);
goog.addDependency('../../../../src/depE.js', ['pow.e'], [], false);
goog.addDependency('../../../../src/main.js', ['pow.main'], ['pow.a', 'pow.b'], false);
